// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbxwtDOcmejmYKtPB9s5iWcSKb7jEo63w',
    appId: '1:30038401477:web:b3448a62226cb01286ebac',
    messagingSenderId: '30038401477',
    projectId: 'authflow-17f99',
    authDomain: 'authflow-17f99.firebaseapp.com',
    storageBucket: 'authflow-17f99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFU4GPH458u8FJft-sd-xhnFVPIjt6MU8',
    appId: '1:30038401477:android:f9848d80bd7d81b286ebac',
    messagingSenderId: '30038401477',
    projectId: 'authflow-17f99',
    storageBucket: 'authflow-17f99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBmRecF2Au8FjSffw0PXOuVB4rutW33pE',
    appId: '1:30038401477:ios:42f5fb240f5640d186ebac',
    messagingSenderId: '30038401477',
    projectId: 'authflow-17f99',
    storageBucket: 'authflow-17f99.firebasestorage.app',
    iosBundleId: 'com.example.authFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBmRecF2Au8FjSffw0PXOuVB4rutW33pE',
    appId: '1:30038401477:ios:42f5fb240f5640d186ebac',
    messagingSenderId: '30038401477',
    projectId: 'authflow-17f99',
    storageBucket: 'authflow-17f99.firebasestorage.app',
    iosBundleId: 'com.example.authFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbxwtDOcmejmYKtPB9s5iWcSKb7jEo63w',
    appId: '1:30038401477:web:a19789e1c9fcd62686ebac',
    messagingSenderId: '30038401477',
    projectId: 'authflow-17f99',
    authDomain: 'authflow-17f99.firebaseapp.com',
    storageBucket: 'authflow-17f99.firebasestorage.app',
  );
}
